### ISSUE TITLE
Versión en rubygems obsoleta

### ISSUE THREAD

**Issue by aldrinmartoq** [Numerico/rut-chileno#2]
No tiene el código actualizado, gracias.

```ruby
2.3.1 :002 > RUT::formatear
NoMethodError: undefined method `formatear' for RUT:Module
```

**Comment by Numerico** [comment]
No tengo tiempo de actualizar este proyecto ya.
Puede que haya otro fork que esté más activo, o si te animas a forkearlo y actualizarlo tal vez te puedo apoyar con comentarios.
Es software libre, está todo bien mientras se respete la licencia https://endefensadelsl.org/ppl_deed_es.html
Gracias
